name: Release

inputs:
  github_token:
    description: Github repository access token
    required: true
  node_version:
    description: Node version
    default: 16
    required: false

runs:
  using: composite
  steps:
    - name: Clone Repo
      uses: actions/checkout@v2
      with:
        # here's why path is needed: https://github.com/orgs/community/discussions/25800
        path: ${{ github.repository }}
        persist-credentials: false
        fetch-depth: 1

    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}

    - run: |-
        if [[ "${{ steps.npm-cache.outputs.cache-hit }}" != "true" ]]; then
          npm ci --quiet --no-progress
        fi
      shell: bash
      working-directory: ${{ github.repository }}

    - name: Build
      run: npm run build --if-present
      shell: bash
      working-directory: ${{ github.repository }}

    - name: Package
      run: npm run package --if-present
      shell: bash
      working-directory: ${{ github.repository }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 0.14.11

    - name: Release
      run: |
        npm run release
      shell: bash
      working-directory: ${{ github.repository }}
      env:
        GH_TOKEN: ${{inputs.github_token}}
        GITHUB_TOKEN: ${{inputs.github_token}}
        CI: true
