name: On Push non-main

on:
  push:
    branches-ignore:
      - main

env:
  TF_VERSION: 1.2.9

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ./.github/actions/terraform-plan
        with:
          environment: "dev"
          commit_sha: ${{ github.sha }}
          tf_directory: examples/dog_food
          tf_version: ${{ env.TF_VERSION }}
